### ISSUE TITLE
macos: script X is running in background.

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#37]
master branch: Do you guys get this?
It should be start a new instance right? Every time I hit a key it should run a new instance of a key script.
However, this only seems to occur for a handful of keys. I am not sure which yet. But it did happen with
H and J for me just now.

![Screen Shot 2020-08-28 at 9 57 46 AM](https://user-images.githubusercontent.com/5650722/91537284-543c1f00-e916-11ea-88b8-9f76a15a9f46.png)

**Comment by molleweide** [comment]
I hit remember and new instance and now things seem to run fine

**Comment by molleweide** [comment]
I am going to reinstall RK bc it feels like this could have something todo with the fact that I haven't pulled master in a while.

**Comment by molleweide** [comment]
The issue seems to persist after having reinstalled RK.

**Comment by gwatcha** [comment]
Yes that is expected, and you should just check 'remember' and 'new instance'. Basically the script bound to the key press becomes the feedback window if no feedback window is open, or the binding list window if you are opening it. Since the window is still open when pressing the key again, reaper automatically shows this dialog.
