### ISSUE TITLE
midi_record mode?

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#41]
# midi record mode feature

I have been thinking about trying to create a mode for programming and recording midi with my keyboard.
Upon doing this I found out that one cannot use the regular keyboard but I am thinking that it wouldn't
be so hard to build a custom mode for recording midi?
I just came up with the idea so I haven't sketched it out or anything but I thought I'd just mention
it here so that we can talk about it. Also if I create something I'll push it up and get back. I have to
read up on how to create a new mode etc.

I have an idea also that it would be pretty cool if one could use tap tempo in order to trigger and start
recording events. This way one could move around the midi editor and quickly record a couple drum notes
where the edit cursor is.

## "midi_rhythm" mode

If all notes on keyboard recorded the current note in midi editor or left hand keys record drum triggers
and right hand controls velocity.

1. I move to C3 double tempo tap > record kick drum
2. then move up to A3 double tap > record snare notes
3. move up to hihat and record some notes

## "midi_key" mode

the keyboard is mapped out where every key is an action command that either triggers a note or
switches oct etc.

it would be quite cool if one had the ability to remap ones midi keyboard as one choses. So that
the keyboard becomes a custom midi drum trigger/keyboard. And why not throw chords on top of it also somehow.

**Comment by gwatcha** [comment]
Cool ideas man! Personally, I don't use that many keys in the midi editor, as I found the most convenient way to record, dub, or replace midi for me is to play is to just set the record mode, and set up a record section with the 'r' operator. I designed RK for this method, so one can have their left hand on the computer keyboard, and right hand on the midi keyboard in these cases.

Your way has the advantage that you could create and alter songs faster than real time. I imagine if these modes get realized and your fingers learn to use them, you could probably make midi items very fast! 

Since this project is mostly for myself, and I'm doing lot's of other things right now, I won't be implementing this. If you want to try yourself, [here](https://gwatcha.github.io/reaper-keys/configuration/advanced.html) is a relevant page from the documentation. 

I'm not sure what you mean by the "tap tempo in order to trigger and start
recording events", but it seems like you want to use the keyboard as a midi keyboard, right? So you move to C3, play, and tap in the notes. I think that may be difficult to make, maybe you could find a keyboard->midi VST? Or use a midi keyboard? A quick search and [this](https://freevstplugins.net/midikeyboard/) turned up. You could put it at the start of your fx chain, start recording, alt+tab to it, and use your keyboard as a midi controller. This may implement some of the 'midi_key' case.

**Comment by molleweide** [comment]
dude thanks for recommending me and checking out my ideas. I fully understand you situation man but my intention is also to implement these things myself so that I can contribute to the project. I have some insane retarded ideas that I want to try out but it is fun to discuss the ideas first before I get too deep into my own implementations since I am just learning how to use RK and Lua but I am really looking forward to getting really deep with creating new modes!!!! As I mentionned before this is the coolest project ever and I really want to be able to help on a more large scale by really adding more generalized pieces that we could really benefit from together.

**Comment by molleweide** [comment]
I want to build out keyboard midi programming and learn from it bc I want be good at programming midi when I am flying and am on the road etc. I am wondering how good kb programming could become if I try to be as innovative as possible.

**Comment by molleweide** [comment]
I have also started thinking about how we could easilly create complex sends
and recieves easilly with RK. I think that I have come up with a good idea and
I'll create a PR when my first demo is in place.

**Comment by gwatcha** [comment]
> I want to build out keyboard midi programming and learn from it bc I want be good at programming midi when I am flying and am on the road etc. I am wondering how good kb programming could become if I try to be as innovative as possible.

Interesting! Good luck with it. 

> I have also started thinking about how we could easilly create complex sends
and recieves easilly with RK. I think that I have come up with a good idea and
I'll create a PR when my first demo is in place.

Oh the sends and receives sounds interesting! I'll wait for that PR. Be sure to pull in the master branch first though, so there are no conflicts.

**Comment by molleweide** [comment]
Unrelated, which linux are u using Mike?

**Comment by gwatcha** [comment]
I am using Manjaro
