### ISSUE TITLE
Shifted Symbols Not Registering

### ISSUE THREAD

**Issue by jonch070** [gwatcha/reaper-keys#75]
The symbols #$%^&*() are not recognized by reaper keys. If i add them as a shortcut in the actions list it works but they are reset every time I open reaper. 

gif below shows me trying to split with % as an example. When I restart reaper the fix no longer works. 

![shifted key issue](https://github.com/user-attachments/assets/30e4e6d9-98a6-4768-94c2-a718b8320928)

**Comment by myrrc** [comment]
What is reaper version, reaper-keys revision and your system?
Can you attach the generated reaper-keys.ReaperKeyMap?

**Comment by molleweide** [comment]
> What is reaper version, reaper-keys revision and your system? Can you attach the generated reaper-keys.ReaperKeyMap?

did you ever find out in which version reaper started treating shifted characters (or whatever it was) differently?

**Comment by myrrc** [comment]
> did you ever find out in which version reaper started treating shifted characters (or whatever it was) differently?

The behaviour didn't change during last versions for Linux, at least. Reaper treats
shifted characters separately by decrementing modifier id, and that behavior is
reproduced in the installer. Maybe macos/windows version is slightly different
hence I ask for the keymap file.

https://mespotin.uber.space/Ultraschall/Reaper-Filetype-Descriptions.html#Reaper-kb.ini
(Keys and Shortcuts)

**Comment by jonch070** [comment]
hey @myrrc here is my reaper-keys.ReaperKeyMap where i have manually added back the shortcuts I need, although this is not presearved when i restart reaper. Please let me know if you would like me to send what i was working with without those. It seemed that "shift 3" was included in the reaper-keys.ReaperKeyMap when i first cloned but not "#"
[reaper-keys.ReaperKeyMap.zip](https://github.com/user-attachments/files/16592822/reaper-keys.ReaperKeyMap.zip)

Im using the current version of reaper, and for the version of reaper keys im using i've modified a bit if you look at my fork. Im on mac sonoma

let me know if you need any other info!! happy to help troubleshoot anything you need, I'm more on the composer side and not a dev so if you need a "dumb guy test" I'm your man

**Comment by myrrc** [comment]
Launch "install-reaper-keys.lua", import the generated keymap and send it here.
I need the reaper-keys keymap only, not all of your keybindings.
Current version of reaper i.e. 7.19?

In the file you sent me there are bindings for shift+{1-9} for midi context but not for main context,
so I suppose the issue is in the installer for macos or, probably, your manual intervention reset
them. If latter is the case, re-import would solve that.

KEY 5 53 _reaper_keys__midi 32060		 # MIDI Editor : Shift+5 : OVERRIDE DEFAULT : reaper-keys

**Comment by jonch070** [comment]
[reaper-keys.ReaperKeyMap.zip](https://github.com/user-attachments/files/16594343/reaper-keys.ReaperKeyMap.zip)
here it is! I ran the installer again and imported this generated keymap. same issues persist

yep, 7.19

**Comment by molleweide** [comment]
> > did you ever find out in which version reaper started treating shifted characters (or whatever it was) differently?
> 
> The behaviour didn't change during last versions for Linux, at least. Reaper treats
> shifted characters separately by decrementing modifier id, and that behavior is
> reproduced in the installer. Maybe macos/windows version is slightly different
> hence I ask for the keymap file.
> 
> https://mespotin.uber.space/Ultraschall/Reaper-Filetype-Descriptions.html#Reaper-kb.ini
> (Keys and Shortcuts)
> 

Yeah, no it changed somwhere btw 2-4 years ago. All binds worked perfectly before.
I added a shift suffix to all binds in the script to make it work for current versions when i was discussing with meapotine a while back

**Comment by myrrc** [comment]
So the keymap is generated correctly and includes shift+numbers, but on import something bad happens.
Can you update to latest revision, back up your keybindings to some file, reset them
(Actions > Show action list > Key map > reset all shortcuts in all sections to defaults),
import the keymap again (import all sections), and then send me the reaper-kb.ini file
(or, otherwise, export the keymap as you did before)?

I'll have a chance to test reaper-keys on macos early next week, hopefully.

**Comment by jonch070** [comment]
did a clean install on a portable and the issue seems to persist!!
[reaper-kb.ini.zip](https://github.com/user-attachments/files/16630464/reaper-kb.ini.zip)

**Comment by myrrc** [comment]
Ok, so it's definitely a MacOS import issue. I'll have a look next week

**Comment by jonch070** [comment]
hey @myrrc , any news on any of this stuff? happy to test if you need!

**Comment by myrrc** [comment]
Hi, currently I don't have time to fix this, sorry.
I have estimates to see it, but it's probably late October or start of November.

**Comment by myrrc** [comment]
@jonch070 I think i fixed it, have a look
